---
title: "R Notebook"
output: html_notebook
---

```{r}
library(DESeq2)
library(MCMCpack)
library(dplyr)
library(ggplot2)
library(purrr)
library(stringr)
library(tidyr)
set.seed(1234)

theme_min <- theme_minimal() + 
  theme(
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "#f7f7f7"),
    panel.border = element_rect(fill = NA, color = "#0c0c0c", size = 0.6),
    axis.text = element_text(size = 14),
    axis.title = element_text(size = 16),
    legend.position = "bottom"
  )
theme_set(theme_min)
```

```{r}
parameters <- list(
  data = list(D = 2000, K1 = 4, K2 = 2, lambda_theta = 1, lambda_beta = 0.5, delta = 0.5, active_prop = 0.1),
  experiment = list(N1 = 20, N2 = 20, depth = 10000)
)

```

```{r}
generate_samples <- function(p, group = 1) {
  # extract parameters
  D <- p$data$D 
  K1 <- p$data$K1
  K2 <- p$data$K2
  lambda_theta <- rep(p$data$lambda_theta, K1 + K2)
  lambda_beta <- rep(p$data$lambda_beta, D)
  delta <- p$data$delta
  active_prop <- p$data$active_prop
  N1 <- p$experiment$N1
  N2 <- p$experiment$N2
  depth <- p$experiment$depth
  
  # simulate latent factors
  v <- rep(delta, K1 + K2)
  v[1:K1] <- -(v[1:K1])
  
  theta <- rbind(
    rdirichlet(N1, lambda_theta),
    rdirichlet(N2, lambda_theta + v)
  )
  
  differential_asvs <- rbinom(D, 1, active_prop)
  beta <- t(rdirichlet(K1 + K2, lambda_beta))
  beta[differential_asvs == 0, (K1 + 1):ncol(beta)] <- 0
  eta <- theta %*% t(beta)
  
  # simulate data based on factors
  samples <- matrix(nrow = N1 + N2, ncol = D)
  for (i in seq_len(nrow(eta))) {
    samples[i, ] <- t(rmultinom(1, depth, eta[i, ]))
  }
  
  reshape_result(samples, N1, N2, differential_asvs)
}

reshape_result <- function(samples, N1, N2, differential_asvs) {
  samples <- data.frame(samples) %>%
    mutate(
      group = c(rep(1, N1), rep(2, N2)), 
      id = 1:(N1 + N2),
      group = as.factor(group),
      id = as.factor(id)
    ) %>%
    pivot_longer(-group:-id, names_to = "asv")
  
  differential_df <- data.frame(
    asv = str_c("X", seq_along(differential_asvs)),
    differential = as.factor(differential_asvs)
  )
  
  samples %>%
    left_join(differential_df)
}


samples <- generate_samples(parameters)
```

For most species (top row), there is no difference between term and preterm. But
for the preterm (bottom row), a subset of the species are differentially
abundant.

```{r}
ggplot(samples) +
  geom_histogram(aes(value, fill = group),binwidth = 2, position = "identity", alpha = 0.8) + 
  facet_grid(differential ~ ., scale = "free_y")
```

```{r, fig.width = 8, fig.height = 4}
samples %>%
  filter(differential == "1") %>%
  filter(asv %in% sample(unique(asv), 8)) %>%
  ggplot() +
  geom_histogram(aes(value, fill = group), binwidth = 1, position = "identity", alpha = 0.8) +
  facet_wrap(~ asv , scale = "free_y", ncol = 4)

samples %>%
  filter(differential == "0") %>%
  filter(asv %in% sample(unique(asv), 8)) %>%
  ggplot() +
  geom_histogram(aes(value, fill = group), binwidth = 1, position = "identity", alpha = 0.8) +
  facet_wrap(~ asv , scale = "free_y", ncol = 4)
```


```{r}
samples_wide <- samples %>%
  select(id, group, asv, value) %>%
  pivot_wider(asv, id)
dds <- DESeqDataSetFromMatrix(countData = samples_wide %>% select(-asv),
                              colData = samples %>% filter(asv == "X1") %>% select(group, id),
                              design = ~ group)
mdata <- samples %>% filter(id == "1") %>% select(asv, differential)
mcols(dds) <- DataFrame(mcols(dds), mdata)
```

```{r}
dds <- dds %>%
  estimateSizeFactors(type = "poscounts") %>%
  DESeq(fitType = "local")
res <- results(dds)
res <- bind_cols(as.data.frame(mcols(dds)), as.data.frame(res))
```

```{r}
ggplot(res) +
  geom_histogram(aes(WaldStatistic_group_2_vs_1, fill = differential), alpha = 0.9, position = "identity") +
  scale_fill_brewer(palette = "Set2")
#ggsave("figures/deseq_results_topics.png")
```
