---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r, echo = FALSE}
library(knitr)
opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r}
library(edgeR)
library(ggdist)
library(glmnet)
library(multtest)
library(tidyverse)
source("mirror.R")
source("mirror-demo.R")
theme_set(theme_bw())
set.seed(20230714)
```

### $p$-value Histograms

```{r}
cols <- c("#F27A5E", "#15AEBF")

simulate_pvalues(200, 1e4) |>
  plot_pval()
ggsave("../figure/histogram-1.svg")
simulate_pvalues(200, 1e4, nonnull_frac = 0.1) |>
  plot_pval()
ggsave("../figure/histogram-2.svg")
simulate_pvalues(200, 1e4, nonnull_frac = 0.1) |>
  plot_pval(facet = FALSE)
ggsave("../figure/histogram-3.svg")
```
```{r}
p_values <- simulate_pvalues(200, 1e4)

h <- 0.01
sorted_values <- p_values |>
  arrange(p_value) |>
  mutate(
    bin = cut(p_value, seq(0, 1, by = h)),
    bin_low = as.numeric(str_extract(bin, "[0-9\\.]+"))
  ) |>
  group_by(bin_low) |>
  summarise(count = n()) |>
  ungroup() |>
  mutate(
    count = count / n(),
    sum_count = h * cumsum(count)
  )
  
ggplot(sorted_values) +
  geom_bar(aes(bin_low, count), stat = "identity", width = .015) +
  scale_y_continuous(expand = c(0, 0, 0.1, 0)) +
  scale_x_continuous(expand = c(0, 0)) +
  labs(x = "p-value", y = "Density")
ggsave("../figure/cdf-transformation-1.png", width = 4, height = 2.5)

ggplot(sorted_values) +
  geom_bar(aes(bin_low, sum_count), stat = "identity", width = .015) +
  scale_y_continuous(expand = c(0, 0)) +
  scale_x_continuous(expand = c(0, 0)) +
  labs(x = "p-value", y = "Cumulative Density")

ggsave("../figure/cdf-transformation-2.png", width = 4, height = 2.5)
```

### NB Miscalibration

```{r}
M <- 2000
nonnull <- 500
mu0 <- rep(5, M)
mu1 <- mu0
effect <- 2
mu1[1:nonnull] <- mu0[1:nonnull] * sample(c(effect, 1 / effect), nonnull, replace = TRUE)

x <- list(
   disease = nb_matrix(mu1, size = 1),
   healthy = nb_matrix(mu0, size = 1) 
  ) |>
  map(~ calcNormFactors(DGEList(t(.)))) |>
  map(~ as_tibble(t(cpm(., log = TRUE)))) |>
  bind_rows(.id = "state")
```

```{r}
x |>
  pivot_longer(-state, names_to = "hypothesis") |>
  mutate(hypothesis = as.integer(str_extract(hypothesis, "[0-9]+"))) |>
  filter(
    hypothesis %in% c(1:10, (nonnull + 1):(nonnull + 10))
  ) |>
  mutate(
    null = ifelse(hypothesis <= nonnull, "Nonnull", "Null"),
    null = factor(null, levels = c("Nonnull", "Null"))
  ) |>
  ggplot() +
  stat_pointinterval(
    aes(as.factor(hypothesis), value, col = state),
    alpha = 0.6, width = 2
  ) +
  scale_color_manual(values = cols) +
  facet_wrap(~ null, scale = "free_x", ncol = 1)
```


```{r}
p_values <- list()
ix <- seq_len(nrow(x) / 2)

for (j in seq(2, ncol(x))) {
  p_values[[j]] <- tibble(
    hypothesis = j - 1,
    p_value = t.test(x[ix, j], x[-ix, j])$p.value
  )
}

p_values <- bind_rows(p_values) |>
  mutate(nonnull = hypothesis %in% seq_len(nonnull))

ggplot(p_values) +
  geom_histogram(aes(p_value, stat(density)), binwidth = 0.025) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0, 0.1, 0)) +
  labs(x = "p-value", y = "Density")

ggsave("../figure/miscalibration_histogram_merged.png", width = 8, height = 4)

p_values |>
  mutate(nonnull = ifelse(nonnull, "Nonnull", "Null")) |>
  ggplot() +
  geom_histogram(
    aes(p_value, stat(density), fill = nonnull),
    binwidth = 0.025
  ) +
  scale_y_continuous(expand = c(0, 0, 0.1, 0)) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_fill_manual(values = cols, guide = FALSE) +
  facet_grid(nonnull ~ ., scales = "free_y") +
  labs(x = "p-value", y = "Density") +
  theme(strip.text.y = element_text(angle = 0, size = 14))

ggsave("../figure/miscalibration_histogram.png", width = 8, height = 4)
```
```{r}
selection_bh <- mt.rawp2adjp(p_values$p_value, proc = "BH", alpha = 0.1)$adjp |>
  mt.reject(alpha = 0.1)

selection_bh <- which(selection_bh$which[, "BH"])
metrics(selection_bh, nonnull)
```

### Using Mirrors

```{r}
x_ <- x |>
  select(-state) |>
  as.matrix()
ms <- map(1:20, ~ glmnet_mirror(x_, x$state))
m_df <- map_dfr(ms, ~ tibble(m = ., ix = seq_along(.)), .id = "replicate") |>
  mutate(
    nonnull = ix %in% seq_len(nonnull),
    nonnull = ifelse(nonnull, "Nonnull", "Null")
  )
```


```{r}
ggplot(m_df) +
  geom_histogram(aes(m), binwidth = 0.0005) +
  scale_y_continuous(expand = c(0, 0, 0.05, 0)) +
  scale_x_continuous(expand = c(0, 0))

ggplot(m_df) +
  geom_histogram(
    aes(m, fill = nonnull),
    position = "identity",
    alpha = 0.9, binwidth = 0.0005
  ) +
  scale_y_continuous(expand = c(0, 0, 0.05, 0)) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_fill_manual(values = cols)
```


```{r}
selection_mirror <- which(multiple_data_splitting(ms))
metrics(selection_mirror, nonnull)
```