---
title: "Context.Rmd"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(colorspace)
#library(IHW)
source("context.R")
theme_set(theme_bw())
set.seed(20230714)
```

```{r}
N <- 50
J <- c(200, 200)
hyper <- list(a = .4, h = 10)
```

```{r}
x <- sample(0:1, N * J[1], replace = TRUE) |>
  matrix(N, J[1])

dists <- abs(outer((1:J[1])/J[1], (1:J[2])/J[2], "-"))
prob <- hyper$a * exp(-hyper$h * dists)
beta <- matbern(J, prob)
y <- x %*% beta + matnorm(N, J[2], 0, 0.1)
```

```{r, fig.width = 6, fig.height = 6}
as_tibble(beta) |>
  mutate(I = row_number()) |>
  pivot_longer(-I, names_to = "J") |>
  mutate(J = as.integer(str_extract(J, "[0-9]+"))) |>
  ggplot() +
  geom_tile(
    aes(I, J, fill = factor(value), col = factor(value))
  ) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  scale_fill_manual(values = c(lighten("#0d6f7a", .96), "#ec4017"), guide = FALSE) +
  scale_color_manual(values = c(lighten("#0d6f7a", .96), "#ec4017"), guide = FALSE) +
  coord_fixed() +
  theme(
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
  )

ggsave("../figure/beta_heatmap.png", width=6, height=6)
```


```{r}
p_values <- matrix(0, J[1], J[2])

for (j1 in seq_len(J[1])) {
  if (j1 %% 10 == 0) {
    print(j1)
  }

  for (j2 in seq_len(J[2])) {
    p_values[j1, j2] <- cor.test(y[, j2], x[, j1])$p.value
  }
}
``` 
```{r, fig.width = 3.5, fig.height = 7}
p_df <- as_tibble(p_values) |>
  mutate(J1 = row_number()) |>
  pivot_longer(-J1, names_to = "J2", values_to = "p") |>
  mutate(
    J1_frac = as.integer(J1) / J[1],
    J2_frac = as.integer(str_extract(J2, "[0-9]+")) / J[2],
    dist = abs(J1_frac - J2_frac),
    nearby = ifelse(dist < 0.1, "Nearby", "Distant"),
    nearby = factor(nearby, levels = c("Nearby", "Distant"))
  )

ggplot(p_df) +
  geom_histogram(aes(p, stat(density))) +
  scale_y_continuous(expand = c(0, 0, 0, .5)) +
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 0.25, 0.5, 0.75)) +
  facet_grid(nearby ~ .) +
  labs(x = "p-values", y = "Density") +
  theme(
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14),
    panel.grid = element_blank(),
    strip.text = element_text(size = 14)
  )

ggsave("../figure/context_p_values_histogram.png", height = 4, width = 6)
```

```{r}
p_list <- list(p_values[dists < 0.1], p_values[dists >= 0.1])
thresholds <- seq(1e-4, .005, length.out = 100)
estimates <- estimate_fdr_vec(p_list, thresholds)

fdr_boundary <- estimates$fdr |>
  filter(fdr_hat < 0.1) |>
  group_by(t1) |>
  summarise(max_t2 = max(t2))
```

```{r}
estimates$fdr |>
  filter(t2 < 0.001) |>
  ggplot() +
  geom_tile(aes(t1, t2, fill = fdr_hat, col = fdr_hat)) +
  scale_fill_gradient2(high = "#0d6f7a", mid = "#F7F7F7", low = "#ec4017", midpoint = 0.1) +
  scale_color_gradient2(high = "#0d6f7a", mid = "#F7F7F7", low = "#ec4017", midpoint = 0.1) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  geom_step(data = fdr_boundary, aes(t1, max_t2), linewidth = 1.25) +
  labs(
    x = "Threshold (Nearby)", 
    y = "Threshold (Faraway)",
    col = expression(widehat(FDR)(t)),
    fill = expression(widehat(FDR)(t))
  ) +
  theme(
    legend.position = "bottom",
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 10),
  )

ggsave("../figure/optimal-thresholds-1.png", height = 4, width = 6.5)
```

```{r}
optimal_thresholds <- estimates$rejections |>
  left_join(estimates$fdr) |>
  filter(t2 < 0.001, fdr_hat < 0.1) |>
  slice_max(rejections) |>
  select(t1, t2)
 
estimates$rejection |>
  filter(t2 < 0.001) |>
  ggplot() +
  geom_tile(aes(t1, t2, fill = rejections, col = rejections)) +
  scale_fill_gradient2(high = "#0d6f7a", mid = "#F7F7F7", low = "#ec4017", midpoint = 299) +
  scale_color_gradient2(high = "#0d6f7a", mid = "#F7F7F7", low = "#ec4017", midpoint = 299) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  geom_step(data = fdr_boundary, aes(t1, max_t2), linewidth = 1.25) +
  labs(
    x = "Threshold (Nearby)", 
    y = "Threshold (Faraway)",
    col = "# Rejections",
    fill = "# Rejections"
  ) +
  geom_point(data = optimal_thresholds, aes(t1, t2), col = "red", size = 10) +
  theme(
    legend.position = "bottom",
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12),
  )

ggsave("../figure/optimal-thresholds-2.png", height= 4, width = 6.5)
```

```{r, fig.width = 6.5, fig.height = 3}
library(fdrtool)
set.seed(20230714)
z <- rexp(2500)
g <- ecdf(z) |>
  grenander()

k <- density(z)

tibble(
    x = c(g$x.knots, k$x), 
    f = c(g$f.knots, k$y),
    method = c(rep("Grenander", length(g$x.knots)), rep("Kernel", length(k$x)))
  ) |>
  ggplot() +
  geom_area(aes(x, f, fill = method), stat = "identity", alpha = 0.65) +
  labs(fill = "Method", x = "x", y = "Estimated Density", title = "Density Estimates from Exp(1) Draws") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0, 0.1, 0)) +
  scale_fill_manual(values = c("#D979A6", "#2A8C7A"))

ggsave("../figure/grenander_comparison.png")
```