---
title: Optimal Transport Examples
author: Kris Sankaran
output: pdf_document
---

```{r}
library(tidyverse)
library(T4transport)
library(patchwork)
theme_set(theme_classic())
```

```{r}
N <- 1e5
df <- tibble(
  id = 1:N,
  x = rnorm(N),
  y = rnorm(N)
) |>
  pivot_longer(-id)


ggplot(df) +
  geom_histogram(aes(value, fill = name), position = "identity", alpha = 0.8, binwidth = 0.1)
```

```{r}
my_margins <- function(df0, df1, df2, ymax = 2.2e4, xmax = 6) {
  p0 <- ggplot(df0) +
    geom_line(aes(start, end), linewidth = 3) +
    geom_vline(xintercept = 0) +
    geom_hline(yintercept = 0) +
    coord_fixed() +
    scale_x_continuous(expand = c(0, 0), limits = c(-6, 6)) +
    scale_y_continuous(expand = c(0, 0), limits = c(-6, xmax)) +
    theme_void()

  p1 <- ggplot(df1) +
    geom_histogram(aes(value), binwidth = 0.1) +
    coord_flip() +
    scale_x_continuous(expand = c(0, 0), limits = c(-6, xmax)) +
    scale_y_reverse(expand = c(0, 0), limits = c(ymax, 0)) +
    theme_void() +
    theme(legend.position = "none")

  p2 <- ggplot(df2) +
    geom_histogram(aes(value), binwidth = 0.1) +
    scale_x_continuous(expand = c(0, 0), limits = c(-6, 6)) +
    scale_y_reverse(expand = c(0, 0), limits = c(2.2e4, 0)) +
    theme_void() +
    theme(legend.position = "none")

  p3 <- ggplot()
  (p1 + p0 + p3 + p2) +
    plot_layout(
      ncol = 2,
      widths = c(1, 3),
      heights = c(3, 1)
    )
}
```

```{r}
N <- 5e5
df0 <- tibble(start = -5:5, end = -5:5)
df1 <- tibble(value = rnorm(N))
df2 <- tibble(value = rnorm(N))
my_margins(df0, df1, df2)
```

```{r}
df0 <- tibble(start = -5:5, end = -4:6)
df1 <- tibble(value = rnorm(N, 1))
df2 <- tibble(value = rnorm(N))
my_margins(df0, df1, df2)
```

```{r}
df0 <- tibble(start = -3:3, end = seq(-9, 9, length.out = 7))
df1 <- tibble(value = rnorm(N, 0, sqrt(3)))
df2 <- tibble(value = rnorm(N))
my_margins(df0, df1, df2)
```

```{r}
x <- seq(-5, 5, length.out = 100)
df0 <- tibble(start = x, end = exp(x))
df1 <- tibble(value = exp(rnorm(N)))
df2 <- tibble(value = rnorm(N))
my_margins(df0, df1, df2, ymax = 4.1e4, xmax = 9)
```